language: python
python:
  - "2.6"
  - "2.7"

before_install:
    - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq
    - sudo apt-get install cmake
    # g++4.8.1
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
  # g++4.8.1
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo apt-get install libstdc++-4.8-dev
  - echo "CXX=$CXX"
  - echo "version `$CXX --version`"
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install --allow-all-external -r requirements2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install protobuf-py3==2.5.1 && pip install --allow-all-external --allow-unverified protobuf-py3 -r requirements3.txt; fi
  - sudo python setup.py develop

# # command to run tests
script: nosetests
